
cc_test(
    name = "test_tires",
    srcs = ["test_tires.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@pooya//src/block",
        "@pooya//src/signal",
        "@pooya//src/solver",
        "//src:tireslib",
    ],
)

cc_test(
    name = "test_buses",
    srcs = ["test_buses.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@pooya//src/block",
        "@pooya//src/signal",
        "@pooya//src/solver",
        "//src:busesLib",
    ],
)
