title: "Create a Vehicle Model from Scratch from C++"
description: "A blog series on building a vehicle model in C++ using Test-Driven Development."
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed

# Set baseurl to "" for a user/organization site, or "/repository-name" for project sites
baseurl: "/Simplecar"
url: "https://chandramouli6890.github.io"

# Enable posts folder
collections:
  posts:
    output: true
