name: Tests Passed
on:
  push:

jobs:
  test-passed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-iostreams-dev libboost-system-dev libboost-filesystem-dev

    - name: Set up Bazel
      uses: bazelbuild/setup-bazelisk@v3

    - name: Run Bazel Tests
      run: |
        bazel clean
        bazel test //... --test_output=errors
